#!/usr/bin/env bash

# selected=$(find ~/ -mindepth 1 -maxdepth 2 -type d | fzf)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$((find ~/Projects/ -mindepth 0 -maxdepth 3 -type d && find ~/.config -mindepth 1 -maxdepth 3 -type d) 2> /dev/null | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

initial_path="$selected"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected \; \
        set-option -t $selected_name @initial_path "$initial_path"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected \; \
        set-option -t $selected_name @initial_path "$initial_path"
fi

tmux switch-client -t $selected_name
